### ISSUE TITLE
I tried running your code. Im getting this error. Any insights?

### ISSUE THREAD

**Issue by AdarshMJ** [MarcTLaw/LorentzianDistanceRetrieval#1]
Hi I am trying to run your code for wordnet-verbs in colab. This is the error Im getting, any insights on how to solve this?

Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/drive/My Drive/LorentzianDistanceRetrieval-master/lorentzian_model.py", line 235, in __getitem__
    if n not in self._weights[t]:
KeyError: tensor(4160)

**Comment by MarcTLaw** [comment]
Hi,

Are you sure you're using pytorch 0.3.1? The way key indices were coded changed in pytorch 0.4 and later....

**Comment by AdarshMJ** [comment]
Hi!
You're right changed the pytorch version and it started working! Thank you!
